### PR TITLE
Invert suspend values for gen3 driver. Fixes JB#49030

### PR DESCRIPTION
**Pull request by ikamaletdinov**
In comparison with Android we sent wrong (inverted) values during screen on/off:
In Android (turning off screen):
[  432.951715] .(1)[2520:wpa_supplicant][wlan]priv_driver_set_suspend_mode:(REQ INFO) priv_driver_set_suspend_mode: Set suspend mode [1]
In Sailfish (turning off screen):
[ 2094.417339]  (0)[2184:connmand][wlan]priv_driver_set_suspend_mode:(REQ INFO) priv_driver_set_suspend_mode: Set suspend mode [0]

### CODE REVIEW

**Comment by monich** [comment]
Hmm, wouldn't that break this plugin on other platforms where it currently does work?

**Comment by ikamaletdinov** [comment]
I think that current logic is wrong for gen3 driver:
https://android.googlesource.com/kernel/mediatek/+/android-mtk-3.18/drivers/misc/mediatek/connectivity/wlan/gen3/os/linux/gl_wext_priv.c#3128

You can see that value 1 is expected to be set to go to suspend mode.

Backtrace for  turning off display:
-- suspend_handle_display_on_off_iface("wlan0", 0); //on_off = 0
-- suspend_handle_display_off()

In case of on_off == 0 value 0 will be sent to function priv_driver_set_suspend_mode in case of gen3 driver.

**Comment by monich** [comment]
@krnlyng what do you think?

**Comment by monich** [comment]
> Hmm, wouldn't that break this plugin on other platforms where it currently does work?

Hmm, not necessarily, if this part of the code wasn't actually being used on other devices and was written "just in case"!

**Comment by mlehtima** [comment]
Suspending with wlan enabled seems to still work also on GeminiPDA after this fix so this is probably good. I do wonder if a better way would be to rename the function parameter and invert the values when calling the suspend_handle_display_on_off_iface instead because now we manually invert the value of that on_off parameter in all uses within that function. Maybe renaming the parameter to "suspend" or something like that would make the code easier to read and also this kind of bugs would be less likely.

**Comment by ikamaletdinov** [comment]
> Suspending with wlan enabled seems to still work also on GeminiPDA after this fix so this is probably good. I do wonder if a better way would be to rename the function parameter and invert the values when calling the suspend_handle_display_on_off_iface instead because now we manually invert the value of that on_off parameter in all uses within that function. Maybe renaming the parameter to "suspend" or something like that would make the code easier to read and also this kind of bugs would be less likely.

nice, I'll refactor suspend_handle_display_on_off_iface method a little bit and will be back to you soon

**Review by mlehtima — APPROVED** [review]

**Pull request merged**
